name: Acebook-group-1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
  workflow_dispatch:


jobs:

  build:

  
    runs-on: ubuntu-latest
    needs: ci

    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Using node 
        uses: actions/setup-node@v1   

      - name: Install
        run: npm install
      