name: Acebook-group-1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: [4.4]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: npm run start:test
      env:
        CI: true
        MONGODB_URI: mongodb://localhost/acebook_test # Access mongoDB Docker container
    - name: ESLint (JS/TS) Action 
  # You may pin to the exact commit or the version.
  # uses: iCrawl/action-eslint@ff2a58dcbc1aaec51815d58e8bf70962c4f2b557
      uses: iCrawl/action-eslint@v1
      with:
    # Custom glob to overwrite which files to lint.
        custom-glob:
    - name: Run tests
      run: npm run test:unit
      env:
        CI: true