name: Acebook-group-1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

   steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create mongoDB Docker container for API testing
      uses: actions/mongo-action@v1.0.1
    - name: Install npm packages
      run: npm install
    - name: Run `npm test`
      run: npm test
      working-directory: ${{ matrix.work-dir }}
      env:
        CI: true
        MONGODB_URI: mongodb://localhost/acebook # Access mongoDB Docker container
        