name: Upload to S3


# on:
#   workflow_run:
#     workflows: ["CI build"]
#     types:
#       - completed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:   

    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: arb280693/acebookgroup1:latest

  # # You may pin to the exact commit or the version.
  # # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
  #     uses: docker/build-push-action@v2.3.0
  #     with:
  #       # Builder instance
  #       builder: # optional
  #       # Build's context is the set of files located in the specified PATH or URL
  #       context: .
  #       # Path to the Dockerfile
  #       file: ./Dockerfile
  #       # List of build-time variables
  #       build-args: # optional
  #       # List of metadata for an image
  #       labels: # optional
  #       # List of tags
  #       tags: arb280693/acebookgroup1:latest
  #       # Always attempt to pull a newer version of the image
  #       pull: # optional, default is false
  #       # Sets the target stage to build
  #       target: # optional
  #       # List of extra privileged entitlement (eg. network.host,security.insecure)
  #       allow: # optional
  #       # Do not use cache when building the image
  #       no-cache: # optional, default is false
  #       # List of target platforms for build
  #       platforms: # optional
  #       # Load is a shorthand for --output=type=docker
  #       load: # optional, default is false
  #       # Push is a shorthand for --output=type=registry
  #       push: true
  #       # List of output destinations (format: type=local,dest=path)
  #       outputs: # optional
  #       # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
  #       cache-from: # optional
  #       # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
  #       cache-to: # optional
  #       # List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
  #       secrets: # optional
  #       # List of secret files to expose to the build (eg. key=filename, MY_SECRET=./secret.txt)
  #       secret-files: # optional
  #       # List of SSH agent socket or keys to expose to the build
  #       ssh: # optional
  #       # GitHub Token used to authenticate against a repository for Git context
  #       github-token: # optional, default is ${{ github.token }}
    
    # - name: GitHub Action for s3_website
    #   uses: justinharringa/actions-s3_website@v1.0

    # - name: Deploy
    #   uses: docker://arb280693/acebookgroup1:v1
    #   with:
    #     args: 'push --site build'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}



#Build Docker image
#Push latest image to Docker Hub
#Pull latest Docker Image
#Push that Docker container to S3