name: Push to Docker Hub


on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:   

    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: arb280693/acebookgroup1
    
    # - name: GitHub Action for s3_website
    #   uses: justinharringa/actions-s3_website@v1.0

    # - name: Deploy
    #   uses: docker://arb280693/acebookgroup1:v1
    #   with:
    #     args: 'push --site build'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}



#Build Docker image
#Push latest image to Docker Hub
#Pull latest Docker Image
#Push that Docker container to S3